### ISSUE TITLE
提点建议

### ISSUE THREAD

**Issue by ifyour** [chinanf-boy/didact-explain#2]
1. 首先感谢你无偿翻译.
2. 但是这个翻译的质量真的...完全是机翻的啊, 看起来好费劲
3. 好好写文档, 不求多美观, 但是最少能有基本的阅读体验, 能和原文的排版一致都好很多了

只是提点建议, 可以随意关闭这条 issue. 祝好~🤓

**Comment by chinanf-boy** [comment]
周末放假, 凌晨🕛两点还不睡

### 1. 我受了, 但并不是无偿, 只是现在没有体现出来

### 2. 本来就是机翻的, 

- 使用 https://github.com/chinanf-boy/translate-mds 完成翻译初稿
- 然后, 屏幕一边是原文, 一边是翻译, 校对的
- 然而我懒,在最后一节的并没有校对, #1 

### 3. 确实丑了点, 你想提交个 关于与https://github.com/hexacta/didact readme.md差不多的样式 的 `Pull` 吗

> 不然, 我懒得换

> 记得图片哪些, 用回 `raw.github`/或者其他来源 的 原始链接, 不要放进 repo

比如 那张大图

```
![img](https://cloud.githubusercontent.com/assets/1911623/26426031/5176c348-40ad-11e7-9f1a-1e2f8840b562.jpeg)
```
![img](https://cloud.githubusercontent.com/assets/1911623/26426031/5176c348-40ad-11e7-9f1a-1e2f8840b562.jpeg)

**Comment by chinanf-boy** [comment]
@ifyour 有兴趣提`Pull`?, 没有我 `Close`了
